FROM nginx:1.21.6-alpine

RUN apk add --no-cache \
        musl \
        tzdata

ENV TZ=America/Detroit

# COPY default.conf /etc/nginx/conf.d/default.conf
# /usr/share/nginx/html NGINX default /root

# # RUN mkdir -p /app/public
# # COPY ./index.html /app/public

# # CMD ["nginx", "-g", "daemon off;"]
# # CMD ["sh", "nginx"]
# # CMD sh nginx
# # CMD nginx -g "daemon off;"
# CMD rc-service nginx start`