FROM mariadb:latest

RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata

# RUN apk update && apk add tzdata
# ENV TZ=America/Detroit

# ENV \
#     MYSQL_ROOT_PASSWORD=secret \
#     MYSQL_USER=tutorial \
#     MYSQL_PASSWORD=secret \
#     MYSQL_DATABASE=tutorial