version: "3"
services:
  # csharp: #docker run -it -v ${PWD}:/work -w /work -p 5001:5000 dennismitchellx/csharp:1.0.0 /bin/sh
  #   container_name: csharp
  #   image: dennismitchellx/csharp:1.0.0
  #   build: ./c#
  #   working_dir: /work
  #   entrypoint: /bin/sh
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #   - ./c#/src/:/work
  #   ports:
  #     - 5001:5000
  # golang: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 dennismitchellx/golang:1.0.0 /bin/sh
  #   container_name: golang
  #   image: dennismitchellx/golang:1.0.3
  #   build: ./golang
  #   working_dir: /work
  #   entrypoint: /bin/sh
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #   - ./golang/src/:/work
  #   ports:
  #     - 5002:5000
  # nodejs: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 dennismitchellx/nodejs:1.0.0 /bin/sh
  #   container_name: nodejs
  #   image: dennismitchellx/nodejs:1.0.0
  #   build: ./nodejs
  #   working_dir: /work
  #   entrypoint: /bin/sh
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #   - ./nodejs/src/:/work
  #   ports:
  #     - 5003:5000
  # python: #docker run -it -v ${PWD}:/work -w /work -p 5004:5000 dennismitchellx/python:1.0.0 /bin/sh
  #   container_name: python
  #   image: dennismitchellx/python:1.0.0
  #   build: ./python
  #   working_dir: /work
  #   entrypoint: /bin/sh
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #   - ./python/src/:/work
  #   ports:
  #     - 5004:5000
  php: #docker run -it -v ${PWD}:/work -w /work -p 5005:5000 dennismitchellx/php:1.0.0 /bin/sh
    #    container_name: php
    image: dennismitchellx/php:1.0.0
    build: ./php
    # working_dir: /work
    # entrypoint: /bin/sh
    # stdin_open: true
    # tty: true
    volumes:
    - ./app:/app
    # - ./php/app:/app
    ports:
      - 5005:5000
  nginx: # docker run -it -v ${PWD}:/work -w /work -p 5006:5000 dennismitchellx/nginx:1.0.0 /bin/sh
        image: dennismitchellx/nginx:1.0.0
        build: ./nginx
        # working_dir: /work
        # entrypoint: /bin/sh
        # stdin_open: true
        # tty: true
        volumes:
        # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        # - ./nginx/app:/app
          - ./app:/usr/share/nginx/html
          # - ./app:/app
        ports:
          - 5006:80
  mysql: # docker run -it -v ${PWD}:/work -w /work -p 5007:5000 dennismitchellx/nginx:1.0.0 /bin/sh
        image: dennismitchellx/mysql:1.0.0
        build: ./mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
        - mysqldata:/var/lib/mysql
        ports:
          - 3306:3306
volumes:
  mysqldata: {}
